-- Add vector embedding column to tasks table
-- This enables semantic search over task descriptions using pgvector

-- Ensure vector extension is enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Add description_embedding column to tasks table
ALTER TABLE tasks 
ADD COLUMN IF NOT EXISTS description_embedding vector(768);

-- Create vector index for efficient similarity search using cosine distance
-- This dramatically improves query performance for vector similarity operations
CREATE INDEX IF NOT EXISTS idx_tasks_description_embedding 
ON tasks 
USING ivfflat (description_embedding vector_cosine_ops)
WITH (lists = 100);

-- Add comment for documentation
COMMENT ON COLUMN tasks.description_embedding IS 'Vector embedding of task title and description for semantic search (768-dimensional, generated by gte-small model)';
