-- Add vector embedding column to tickets table
-- This enables semantic search over ticket descriptions using pgvector

-- Ensure vector extension is enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Add description_embedding column to tickets table
ALTER TABLE tickets 
ADD COLUMN IF NOT EXISTS description_embedding vector(768);

-- Create vector index for efficient similarity search using cosine distance
-- This dramatically improves query performance for vector similarity operations
CREATE INDEX IF NOT EXISTS idx_tickets_description_embedding 
ON tickets 
USING ivfflat (description_embedding vector_cosine_ops)
WITH (lists = 100);

-- Add comment for documentation
COMMENT ON COLUMN tickets.description_embedding IS 'Vector embedding of ticket title and description for semantic search (768-dimensional, generated by gte-small model)';
